version: "3.1"

services:
  db_tienda:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: tienda_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: wialdiru
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret